### PR TITLE
feat(metrics): Add URL to metrics labels

### PR DESCRIPTION
**Pull request by danlsgiga**
Small feature addition.

Sometimes is useful to have the endpoint URL in metrics labels so we can include that as part of alert messages when these metrics are scraped via prometheus.

### CODE REVIEW

**Review by j6nca — APPROVED** [review]

**Comment by danlsgiga** [comment]
@TwiN any feedback on this PR?

**Comment by TwiN** [comment]
Thank you for the contribution!

**Comment by TwiN** [comment]
@danlsgiga I don't do this usually, but I had to revert the PR because I don't have the time to fix this right now.

After merging, I found out that the URL doesn't discard the query parameters, and that's an issue because unfortunately, many people pass tokens as query parameter (e.g. `https://example.org/api/v1/example?token=123`), which would make releasing this a security risk.

If you can make another PR that discards all query parameters (`?token=123`, in the example above), I could merge your feature.

**Comment by danlsgiga** [comment]
Oh, I'm sorry @TwiN, I totally missed this message! I'll look into this and open a new PR! thanks!

**Pull request merged**
