### PR TITLE
Also use `name` attribute in meta tag

### PR DESCRIPTION
**Pull request by salim-b**
Lighthouse (and probably other tools) do not detect `<meta property="description" ... >` but only `<meta name="description" ... >`. According to [this SO answer](https://stackoverflow.com/a/22418095/7196903), the latter is the standard HTML5 way to provide a site's description metadata, while the former is the RDFa way to do the same. According to [another SO answer](https://stackoverflow.com/a/20429551/7196903), it is absolutely valid to provide both attributes in the same meta tag, so here we go.

## Summary

Relevant issue: https://github.com/TwiN/gatus/issues/345

## Checklist

- [ ] Tested and/or added tests to validate that the changes work as intended, if applicable. *-> not actually tested*
- [x] Added the documentation in `README.md`, if applicable. *-> not applicable*

### CODE REVIEW

**Comment by TwiN** [comment]
Can you `make frontend-build`? 🙏

**Comment by salim-b** [comment]
> Can you `make frontend-build`? :pray:

Just tried, but failed to properly set up the required dev environment... I've installed all npm packages that weren't found during `make frontend-build` (including `babel-eslint`) but it still errors:

<details><summary>Log:</summary>

```
$ make frontend-build
npm --prefix web/app run build

> gatus@4.0.0 build
> vue-cli-service build --modern --mode production

All browser targets in the browserslist configuration have supported ES module.
Therefore we don't build two separate bundles for differential loading.


⠴  Building for production...

 ERROR  Failed to compile with 1 error                                                                                                                                                                                                                                                                                                                                    11:55:30 PM

[eslint] 
/home/salim/Code/ad-hoc/gatus/web/app/src/App.vue
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/components/Endpoint.vue
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/components/EndpointGroup.vue
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/components/Endpoints.vue
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/components/Loading.vue
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/components/Pagination.vue
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/components/Settings.vue
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/components/Social.vue
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/components/Tooltip.vue
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/main.js
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/mixins/helper.js
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/router/index.js
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/views/Details.vue
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

/home/salim/Code/ad-hoc/gatus/web/app/src/views/Home.vue
  0:0  error  Parsing error: Cannot find module 'babel-eslint'
Require stack:
- /home/salim/Code/ad-hoc/gatus/node_modules/vue-eslint-parser/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/utils/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/rules/array-bracket-newline.js
- /home/salim/Code/ad-hoc/gatus/node_modules/eslint-plugin-vue/lib/index.js
- /home/salim/Code/ad-hoc/gatus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs

✖ 14 problems (14 errors, 0 warnings)


You may use special comments to disable some warnings.
Use // eslint-disable-next-line to ignore the next line.
Use /* eslint-disable */ to ignore all warnings in a file.
 ERROR  Error: Build failed with errors.
Error: Build failed with errors.
    at /home/salim/Code/ad-hoc/gatus/node_modules/@vue/cli-service/lib/commands/build/index.js:207:23
    at /home/salim/Code/ad-hoc/gatus/node_modules/webpack/lib/webpack.js:148:8
    at /home/salim/Code/ad-hoc/gatus/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/salim/Code/ad-hoc/gatus/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/salim/Code/ad-hoc/gatus/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/home/salim/Code/ad-hoc/gatus/node_modules/webpack/lib/Cache.js:150:23)
    at /home/salim/Code/ad-hoc/gatus/node_modules/webpack/lib/Compiler.js:1225:15
    at Hook.eval [as callAsync] (eval at create (/home/salim/Code/ad-hoc/gatus/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/salim/Code/ad-hoc/gatus/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/home/salim/Code/ad-hoc/gatus/node_modules/webpack/lib/Compiler.js:1218:23)
make: *** [Makefile:37: frontend-build] Error 1

```
</details>

Would be really helpful to have some development setup instructions in the README :grimacing: (I'm no JS dev and have literally zero experience with Vue.js).

**Comment by TwiN** [comment]
Looks like this will be taken care of by #347

**Comment by TwiN** [comment]
Superseded by #347

**Pull request closed without merging**
