### PR TITLE
feat: support SCTP & UDP as endpoint type

### PR DESCRIPTION
**Pull request by ianchen0119**
## Summary

Related Issue: https://github.com/TwiN/gatus/issues/333

I added the handlers on sctp and udp protocol.
Cause I want to use gatus to monitor all the interfaces on 5G core network.

## Checklist

- [x] Tested and/or added tests to validate that the changes work as intended, if applicable.
- [x] Added the documentation in `README.md`, if applicable.

### CODE REVIEW

**Comment by ianchen0119** [comment]
Hi @TwiN 
Would you please help to review this PR?
Many thanks!

**Review by TwiN — CHANGES_REQUESTED** [review]
Can you add tests & document how to monitor an UDP and a SCTP endpoint?

For the documentation part, there's an example here: [Monitoring a TCP endpoint](https://github.com/TwiN/gatus#monitoring-a-tcp-endpoint)

**Comment by ianchen0119** [comment]
@TwiN 

Done 👍

**Review by TwiN — APPROVED** [review]

**Comment by TwiN** [comment]
Thank you for the contribution!

**Pull request merged**
